### ISSUE TITLE
Add new group by country variant of stats endpoint

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-contributions-stats-service#15]
Provide a group-by-country variant of the stats/<hashtag> endpoint so that countries can be visualized on map based. We could show the top countries for our 4 categories i.e. (contributors, total edits, building edits, km of road).

We can discuss having this as a part of stats/<hashtag>/interval endpoint.

**Comment by ElJocho** [comment]
it was decided to only provide the country stats for the entire time-frame, not additionally by interval
